source 'https://rubygems.org'
ruby '1.9.3'

gem 'rails', '4.0.0'
gem 'mysql2'

gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'compass-rails', '2.0.alpha.0'

gem 'devise', '3.1.0'

group :development do
  gem 'quiet_assets'
end