source 'https://rubygems.org'
ruby '1.9.3'

gem 'rails', '4.0.0'

gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'compass-rails', '2.0.alpha.0'

gem 'devise', '3.1.0'
gem 'issuu', '0.3.0'
gem 'will_paginate', '3.0.4'
gem 'awesome_nested_fields', '0.6.1'

group :development do
  gem 'quiet_assets'
  gem 'mysql2'
end

group :production do
  gem 'rails_12factor'
  gem 'pg', '0.16.0'
end